name: delicias_darsy_movil
description: "A new Flutter project for DeliciaSoft bakery management."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & fonts
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

  # Image picker
  image_picker: ^1.1.1

  # HTTP requests
  http: ^1.1.0

  # State management
  provider: ^6.0.5

  # Local storage
  shared_preferences: ^2.2.2

  # Form validation
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17

  # JSON serialization
  json_annotation: ^4.8.1

  # Loading indicators
  flutter_spinkit: ^5.2.0

  # Toast messages
  fluttertoast: ^8.2.4

  # Connectivity
  connectivity_plus: ^5.0.2

  # Date formatting
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo.png