name: delicias_darsy_movil
description: "A new Flutter project for DeliciaSoft bakery management."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI y Estilos
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4

  # Red e Internet
  http: ^1.2.1 # Keeping the higher version
  connectivity_plus: ^5.0.2

  # Formularios y Validación
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17

  # Almacenamiento y estado
  shared_preferences: ^2.2.2
  provider: ^6.0.5

  # Manejo de imágenes
  image_picker: ^1.1.2 # Keeping the higher version

  # Fechas
  intl: ^0.18.1

  # JSON
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo.png